### ISSUE TITLE
Can't start the application with `npm run dev`

### ISSUE THREAD

**Issue by bzg** [backyourstack/backyourstack#372]
Hi! I can't start the application for development.  I configured a new GitHub application, did a `npm install` and then `npm run dev` gives me this: 

```
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src/server/**/* src/routes.js src/lib/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node src/server/index.js`
The static directory has been deprecated in favor of the public directory. https://err.sh/zeit/next.js/static-dir-deprecated
(node:4241) UnhandledPromiseRejectionWarning: SyntaxError: Unsupported regular expression /(?<!node_modules.*)[\\/]node_modules[\\/](react|react-dom|scheduler|prop-types|use-subscription)[\\/]/: TRegex: body of lookbehind assertion too complex; Joni: quantifiers inside lookbehind assertions not supported
    at getBaseWebpackConfig (/home/guerry/backyourstack/node_modules/next/dist/build/webpack-config.js:7:4)
    at HotReloader.getWebpackConfig (/home/guerry/backyourstack/node_modules/next/dist/server/hot-reloader.js:14:1371)
(node:4241) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:4241) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[nodemon] clean exit - waiting for changes before restart
```

I use `nodejs -v v10.15.2`.

Any Idea what I may have overlooked? Thanks!

**Comment by znarf** [comment]
@bzg it's weird, definitely not reproducing. Maybe try with a different node version?

**Comment by bzg** [comment]
Thanks for answering. I will try testing with another version.
 
`npm run start` runs fine btw.

**Comment by bzg** [comment]
Okay, it was definitely a problem with my `npm` version.  Closing this now.  Thanks!
